### ISSUE TITLE
Possible error in url

### ISSUE THREAD

**Issue by AlexSen** [frankperez87/autocheck#2]
Hello, Frank.
I've tried your script and based on your example it returns EMPTY.
I've debugged it and found that you use https://www.autocheck.com/DealerWebLink.jsp po post request. But with all filled fields it returned me 403 error. Don't you know maybe url changed?
![snapshot n001_2015-12-06_19-30-31](https://cloud.githubusercontent.com/assets/6735288/11614871/ca3b8f10-9c4f-11e5-8873-ae626dce8094.png)

**Comment by frankperez87** [comment]
Have you had AutoCheck whitelist your IP address?
